// Generated by CoffeeScript 1.3.1
var lastTime, pts, samples, space;

space = new CanvasSpace().display();

space.bgcolor = '#2d2d2d';

space.ctx.strokeStyle = '#fff';

space.refresh(false);

space.clear("#222");

pts = [];

samples = new SamplePoints();

samples.setBounds(new Rectangle(25, 25).size(space.size.x - 25, space.size.y - 25), true);

samples.poissonSampler(5);

space.bindCanvas("click", function(evt) {});

lastTime = 0;

space.add({
  animate: function(time, frameTime, ctx) {
    var count, s;
    count = 0;
    while (time - lastTime < 25 && count++ < 50) {
      s = samples.sample(10, 'poisson');
      ctx.fillStyle = '#fff';
      if (s) {
        Form.point(ctx, s, 3, true, false, false);
      }
      if (s) {
        samples.to(s);
      }
    }
    return lastTime = time;
  }
});

space.play();

space.stop(50000);
